// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bridges.proto

package birdges

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BridgesService_SetKeys_FullMethodName    = "/Bridges.BridgesService/SetKeys"
	BridgesService_SendByKeys_FullMethodName = "/Bridges.BridgesService/SendByKeys"
	BridgesService_SendAll_FullMethodName    = "/Bridges.BridgesService/SendAll"
)

// BridgesServiceClient is the client API for BridgesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgesServiceClient interface {
	SetKeys(ctx context.Context, in *SetKeysRequest, opts ...grpc.CallOption) (*SetKeysReply, error)
	SendByKeys(ctx context.Context, in *SendByKeysRequest, opts ...grpc.CallOption) (*SendReply, error)
	SendAll(ctx context.Context, in *SendAllRequest, opts ...grpc.CallOption) (*SendReply, error)
}

type bridgesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgesServiceClient(cc grpc.ClientConnInterface) BridgesServiceClient {
	return &bridgesServiceClient{cc}
}

func (c *bridgesServiceClient) SetKeys(ctx context.Context, in *SetKeysRequest, opts ...grpc.CallOption) (*SetKeysReply, error) {
	out := new(SetKeysReply)
	err := c.cc.Invoke(ctx, BridgesService_SetKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgesServiceClient) SendByKeys(ctx context.Context, in *SendByKeysRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, BridgesService_SendByKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgesServiceClient) SendAll(ctx context.Context, in *SendAllRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, BridgesService_SendAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgesServiceServer is the server API for BridgesService service.
// All implementations must embed UnimplementedBridgesServiceServer
// for forward compatibility
type BridgesServiceServer interface {
	SetKeys(context.Context, *SetKeysRequest) (*SetKeysReply, error)
	SendByKeys(context.Context, *SendByKeysRequest) (*SendReply, error)
	SendAll(context.Context, *SendAllRequest) (*SendReply, error)
	mustEmbedUnimplementedBridgesServiceServer()
}

// UnimplementedBridgesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBridgesServiceServer struct {
}

func (UnimplementedBridgesServiceServer) SetKeys(context.Context, *SetKeysRequest) (*SetKeysReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKeys not implemented")
}
func (UnimplementedBridgesServiceServer) SendByKeys(context.Context, *SendByKeysRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendByKeys not implemented")
}
func (UnimplementedBridgesServiceServer) SendAll(context.Context, *SendAllRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAll not implemented")
}
func (UnimplementedBridgesServiceServer) mustEmbedUnimplementedBridgesServiceServer() {}

// UnsafeBridgesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgesServiceServer will
// result in compilation errors.
type UnsafeBridgesServiceServer interface {
	mustEmbedUnimplementedBridgesServiceServer()
}

func RegisterBridgesServiceServer(s grpc.ServiceRegistrar, srv BridgesServiceServer) {
	s.RegisterService(&BridgesService_ServiceDesc, srv)
}

func _BridgesService_SetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgesServiceServer).SetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgesService_SetKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgesServiceServer).SetKeys(ctx, req.(*SetKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgesService_SendByKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendByKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgesServiceServer).SendByKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgesService_SendByKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgesServiceServer).SendByKeys(ctx, req.(*SendByKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgesService_SendAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgesServiceServer).SendAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgesService_SendAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgesServiceServer).SendAll(ctx, req.(*SendAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgesService_ServiceDesc is the grpc.ServiceDesc for BridgesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bridges.BridgesService",
	HandlerType: (*BridgesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetKeys",
			Handler:    _BridgesService_SetKeys_Handler,
		},
		{
			MethodName: "SendByKeys",
			Handler:    _BridgesService_SendByKeys_Handler,
		},
		{
			MethodName: "SendAll",
			Handler:    _BridgesService_SendAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridges.proto",
}
