// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bridges.proto

package birdges

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpireAt int64  `protobuf:"varint,2,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{0}
}

func (x *KeyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type SetKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*KeyInfo `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SetKeysRequest) Reset() {
	*x = SetKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeysRequest) ProtoMessage() {}

func (x *SetKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeysRequest.ProtoReflect.Descriptor instead.
func (*SetKeysRequest) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{1}
}

func (x *SetKeysRequest) GetKeys() []*KeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SetKeysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetKeysReply) Reset() {
	*x = SetKeysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeysReply) ProtoMessage() {}

func (x *SetKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeysReply.ProtoReflect.Descriptor instead.
func (*SetKeysReply) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{2}
}

type SendByKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Evt  string   `protobuf:"bytes,2,opt,name=evt,proto3" json:"evt,omitempty"`
	Data []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendByKeysRequest) Reset() {
	*x = SendByKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendByKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendByKeysRequest) ProtoMessage() {}

func (x *SendByKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendByKeysRequest.ProtoReflect.Descriptor instead.
func (*SendByKeysRequest) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{3}
}

func (x *SendByKeysRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SendByKeysRequest) GetEvt() string {
	if x != nil {
		return x.Evt
	}
	return ""
}

func (x *SendByKeysRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evt      string   `protobuf:"bytes,1,opt,name=evt,proto3" json:"evt,omitempty"`
	Data     []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SkipKeys []string `protobuf:"bytes,3,rep,name=skipKeys,proto3" json:"skipKeys,omitempty"`
}

func (x *SendAllRequest) Reset() {
	*x = SendAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAllRequest) ProtoMessage() {}

func (x *SendAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAllRequest.ProtoReflect.Descriptor instead.
func (*SendAllRequest) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{4}
}

func (x *SendAllRequest) GetEvt() string {
	if x != nil {
		return x.Evt
	}
	return ""
}

func (x *SendAllRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendAllRequest) GetSkipKeys() []string {
	if x != nil {
		return x.SkipKeys
	}
	return nil
}

type SendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendReply) Reset() {
	*x = SendReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridges_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReply) ProtoMessage() {}

func (x *SendReply) ProtoReflect() protoreflect.Message {
	mi := &file_bridges_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReply.ProtoReflect.Descriptor instead.
func (*SendReply) Descriptor() ([]byte, []int) {
	return file_bridges_proto_rawDescGZIP(), []int{5}
}

var File_bridges_proto protoreflect.FileDescriptor

var file_bridges_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22,
	0x36, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x4b, 0x65,
	0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4d, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x76, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x76, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x76, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x76, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xc7, 0x01, 0x0a, 0x0e, 0x42, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x53, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x17, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e,
	0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1a, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x62, 0x69, 0x72, 0x64, 0x67, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bridges_proto_rawDescOnce sync.Once
	file_bridges_proto_rawDescData = file_bridges_proto_rawDesc
)

func file_bridges_proto_rawDescGZIP() []byte {
	file_bridges_proto_rawDescOnce.Do(func() {
		file_bridges_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridges_proto_rawDescData)
	})
	return file_bridges_proto_rawDescData
}

var file_bridges_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bridges_proto_goTypes = []interface{}{
	(*KeyInfo)(nil),           // 0: Bridges.KeyInfo
	(*SetKeysRequest)(nil),    // 1: Bridges.SetKeysRequest
	(*SetKeysReply)(nil),      // 2: Bridges.SetKeysReply
	(*SendByKeysRequest)(nil), // 3: Bridges.SendByKeysRequest
	(*SendAllRequest)(nil),    // 4: Bridges.SendAllRequest
	(*SendReply)(nil),         // 5: Bridges.SendReply
}
var file_bridges_proto_depIdxs = []int32{
	0, // 0: Bridges.SetKeysRequest.keys:type_name -> Bridges.KeyInfo
	1, // 1: Bridges.BridgesService.SetKeys:input_type -> Bridges.SetKeysRequest
	3, // 2: Bridges.BridgesService.SendByKeys:input_type -> Bridges.SendByKeysRequest
	4, // 3: Bridges.BridgesService.SendAll:input_type -> Bridges.SendAllRequest
	2, // 4: Bridges.BridgesService.SetKeys:output_type -> Bridges.SetKeysReply
	5, // 5: Bridges.BridgesService.SendByKeys:output_type -> Bridges.SendReply
	5, // 6: Bridges.BridgesService.SendAll:output_type -> Bridges.SendReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bridges_proto_init() }
func file_bridges_proto_init() {
	if File_bridges_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bridges_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridges_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridges_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKeysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridges_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendByKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridges_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridges_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridges_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridges_proto_goTypes,
		DependencyIndexes: file_bridges_proto_depIdxs,
		MessageInfos:      file_bridges_proto_msgTypes,
	}.Build()
	File_bridges_proto = out.File
	file_bridges_proto_rawDesc = nil
	file_bridges_proto_goTypes = nil
	file_bridges_proto_depIdxs = nil
}
